<?php
declare(strict_types=1);

require __DIR__ . '/../../bootstrap.php';
require_teacher();
header('Content-Type: application/json; charset=utf-8');

function tr_json(array $payload, int $status = 200): never { http_response_code($status); echo json_encode($payload, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function tr_body(): array { $raw=file_get_contents('php://input'); $j=$raw?json_decode($raw,true):[]; return is_array($j)?$j:[]; }
function tr_cfg(): array { $cfg=app_config(); $tc=$cfg['text_check']??[]; return is_array($tc)?$tc:[]; }
function tr_ai_cfg(): array {
  $cfg=app_config(); $tc=tr_cfg(); $ai=$cfg['ai']??[]; if(!is_array($ai))$ai=[];
  $key=trim((string)($ai['api_key'] ?? getenv('OPENAI_API_KEY') ?: ''));
  $model=trim((string)($tc['model'] ?? '')) ?: trim((string)($ai['model'] ?? 'gpt-4o-mini'));
  return ['enabled'=>!empty($ai['enabled']),'api_key'=>$key,'base_url'=>rtrim((string)($ai['base_url']??'https://api.openai.com'),'/'),'model'=>$model,'timeout'=>(int)($ai['timeout_seconds']??60),'provider'=>(string)($tc['provider']??'disabled'),'text_enabled'=>!empty($tc['enabled'])];
}
function tr_enabled(): bool { $c=tr_ai_cfg(); return !empty($c['text_enabled']) && $c['provider']==='ai' && !empty($c['enabled']) && $c['api_key']!=='' && $c['model']!==''; }
function tr_require_ai(): array { $c=tr_ai_cfg(); if(empty($c['text_enabled'])||$c['provider']==='disabled') throw new RuntimeException('Textprüfung ist nicht konfiguriert.'); if($c['provider']!=='ai') throw new RuntimeException('KI-Provider nicht verfügbar.'); if(empty($c['enabled'])) throw new RuntimeException('KI-Provider nicht verfügbar.'); if($c['api_key']==='') throw new RuntimeException('API-Key fehlt.'); if($c['model']==='') throw new RuntimeException('Modell fehlt.'); return $c; }
function tr_is_free_text(array $f): bool { $t=strtolower((string)($f['field_type']??'')); return $t==='text'||$t==='multiline'||(int)($f['is_multiline']??0)===1; }
function tr_reports(PDO $pdo,int $classId,int $tplId,string $year,string $period): array { $st=$pdo->prepare("SELECT s.id student_id, CONCAT(s.last_name, ', ', s.first_name) student_name, ri.id report_id FROM students s JOIN report_instances ri ON ri.student_id=s.id AND ri.template_id=? AND ri.school_year=? AND ri.period_label=? WHERE s.class_id=? AND s.is_active=1 ORDER BY s.last_name,s.first_name,s.id"); $st->execute([$tplId,$year,$period,$classId]); return $st->fetchAll(PDO::FETCH_ASSOC); }
function tr_class_context(PDO $pdo,int $classId): array { $st=$pdo->prepare("SELECT id, template_id, school_year, period_label FROM classes WHERE id=? LIMIT 1"); $st->execute([$classId]); $c=$st->fetch(PDO::FETCH_ASSOC); if(!$c) throw new RuntimeException('Klasse nicht gefunden.'); return ['template_id'=>(int)$c['template_id'],'school_year'=>(string)$c['school_year'],'period_label'=>normalize_class_period_label($c['period_label']??'Standard')]; }
function tr_status(PDO $pdo,int $classId): array {
  $ctx=tr_class_context($pdo,$classId); $tplId=$ctx['template_id'];
  $fields=$pdo->prepare("SELECT id, can_teacher_edit, can_child_edit, is_required, field_type, is_multiline, field_name, label, label_en, meta_json FROM template_fields WHERE template_id=?"); $fields->execute([$tplId]); $rows=$fields->fetchAll(PDO::FETCH_ASSOC);
  $reqTeacher=[]; $reqChild=[]; $free=[];
  foreach($rows as $f){ $meta=json_decode((string)($f['meta_json']??''),true); $meta=is_array($meta)?$meta:[]; $sys=(!empty($meta['system_binding'])||!empty($meta['system_binding_tpl'])); $class=((string)($meta['scope']??'')==='class'||(int)($meta['is_class_field']??0)===1); if($sys||$class) continue; if((int)$f['is_required']===1 && (int)$f['can_teacher_edit']===1)$reqTeacher[]=(int)$f['id']; if((int)$f['is_required']===1 && (int)$f['can_child_edit']===1)$reqChild[]=(int)$f['id']; if((int)$f['can_teacher_edit']===1 && tr_is_free_text($f))$free[(int)$f['id']]=$f; }
  $reports=tr_reports($pdo,$classId,$tplId,$ctx['school_year'],$ctx['period_label']); $unfinished=0; $missing=0;
  $checkVals=function(array $ids,string $source)use($pdo,$reports){ if(!$ids||!$reports)return[]; $rids=array_map(fn($r)=>(int)$r['report_id'],$reports); $inR=implode(',',array_fill(0,count($rids),'?')); $inF=implode(',',array_fill(0,count($ids),'?')); $st=$pdo->prepare("SELECT report_instance_id,template_field_id,value_text FROM field_values WHERE source=? AND report_instance_id IN ($inR) AND template_field_id IN ($inF)"); $st->execute(array_merge([$source],$rids,$ids)); $out=[]; foreach($st->fetchAll(PDO::FETCH_ASSOC) as $v)$out[(int)$v['report_instance_id']][(int)$v['template_field_id']]=(string)($v['value_text']??''); return$out; };
  $tv=$checkVals($reqTeacher,'teacher'); $cv=$checkVals($reqChild,'child');
  foreach($reports as $r){$rid=(int)$r['report_id'];$miss=0;foreach($reqTeacher as $fid) if(trim($tv[$rid][$fid]??'')==='')$miss++; foreach($reqChild as $fid) if(trim($cv[$rid][$fid]??'')==='')$miss++; if($miss>0){$unfinished++;$missing+=$miss;}}
  $ai=tr_ai_cfg(); $tc=tr_cfg(); return ['ok'=>true,'enabled'=>tr_enabled(),'provider'=>$ai['provider'],'model'=>$ai['model'],'max_fields_per_batch'=>max(1,(int)($tc['max_fields_per_batch']??8)),'available'=>tr_enabled()&&$unfinished===0,'unfinished_reports'=>$unfinished,'missing_required_fields'=>$missing,'students_total'=>count($reports),'free_text_fields_total'=>count($free),'message'=>tr_enabled()?($unfinished===0?'':'Textprüfung verfügbar, sobald alle Pflichtfelder abgeschlossen sind.'):'Textprüfung ist derzeit nicht verfügbar.'];
}
function tr_prepare(PDO $pdo,int $classId): array { $s=tr_status($pdo,$classId); if(!$s['available']) return $s+['items'=>[],'estimated_chars'=>0]; $ctx=tr_class_context($pdo,$classId); $tplId=$ctx['template_id']; $reports=tr_reports($pdo,$classId,$tplId,$ctx['school_year'],$ctx['period_label']); $fields=$pdo->prepare("SELECT id, field_name, label, label_en, field_type, is_multiline FROM template_fields WHERE template_id=? AND can_teacher_edit=1"); $fields->execute([$tplId]); $free=[]; foreach($fields->fetchAll(PDO::FETCH_ASSOC) as $f) if(tr_is_free_text($f))$free[(int)$f['id']]=$f; if(!$free||!$reports)return$s+['items'=>[],'estimated_chars'=>0]; $rids=array_map(fn($r)=>(int)$r['report_id'],$reports); $inR=implode(',',array_fill(0,count($rids),'?')); $inF=implode(',',array_fill(0,count($free),'?')); $st=$pdo->prepare("SELECT report_instance_id,template_field_id,value_text FROM field_values WHERE source='teacher' AND report_instance_id IN ($inR) AND template_field_id IN ($inF)"); $st->execute(array_merge($rids,array_keys($free))); $byReport=[]; foreach($reports as $r)$byReport[(int)$r['report_id']]=$r; $items=[];$chars=0; foreach($st->fetchAll(PDO::FETCH_ASSOC) as $v){$text=trim((string)($v['value_text']??'')); if($text==='')continue; $fid=(int)$v['template_field_id']; $rid=(int)$v['report_instance_id']; $f=$free[$fid]; $r=$byReport[$rid]; $chars+=mb_strlen($text); $items[]=['student_id'=>(int)$r['student_id'],'student_name'=>(string)$r['student_name'],'report_id'=>$rid,'field_id'=>$fid,'field_name'=>(string)$f['field_name'],'field_label_de'=>(string)($f['label']??''),'field_label_en'=>(string)($f['label_en']??''),'language'=>'auto','current_text'=>$text]; } return $s+['items'=>$items,'estimated_chars'=>$chars]; }
function tr_prompt(array $items): array { return [['role'=>'system','content'=>'Prüfe aktiv Lernentwicklungsbericht-/Zeugnis-Freitexte auf Rechtschreibung, Grammatik, Zeichensetzung, Sprachstil, Verständlichkeit und sachlichen Zeugnisstil. Bei offensichtlichen Fehlern MUSS eine Empfehlung kommen. Behalte Bedeutung, Bewertung und Aussageabsicht bei. Erfinde keine Inhalte und ergänze keine Beobachtungen. Mache konkrete, minimal-invasive Vorschläge. Antworte ausschließlich als valides JSON: {"suggestions":[{"student_id":number,"report_id":number,"field_id":number,"type":"spelling|grammar|style|translation","severity":"low|medium|high","original_excerpt":"...","suggested_text":"...","explanation":"...","confidence":0.0-1.0}]}. Wenn wirklich nichts zu verbessern ist, suggestions: []. Beispiele: Input "He have made good progress." => grammar Vorschlag "He has made good progress." Input "Der Schüler arbeitet gut mit tun." => grammar/style Vorschlag "Der Schüler arbeitet gut mit."'],['role'=>'user','content'=>json_encode(['items'=>$items],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]]; }
function tr_ai_call(array $messages,array $cfg): string { if(!function_exists('curl_init')) throw new RuntimeException('KI-Provider nicht verfügbar: PHP-cURL fehlt.'); $url=$cfg['base_url'].'/v1/chat/completions'; $payload=['model'=>$cfg['model'],'messages'=>$messages,'temperature'=>0.1,'response_format'=>['type'=>'json_object']]; $ch=curl_init($url); if(!$ch) throw new RuntimeException('KI-Provider nicht verfügbar.'); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Authorization: Bearer '.$cfg['api_key']],CURLOPT_POSTFIELDS=>json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),CURLOPT_TIMEOUT=>max(10,(int)$cfg['timeout'])]); $resp=curl_exec($ch); $code=(int)(curl_getinfo($ch,CURLINFO_HTTP_CODE)?:0); if($resp===false){$err=curl_error($ch);curl_close($ch);throw new RuntimeException('KI-Provider nicht verfügbar: '.$err);} curl_close($ch); $j=json_decode((string)$resp,true); if($code<200||$code>=300) throw new RuntimeException('KI-Fehler: HTTP '.$code); $txt=$j['choices'][0]['message']['content']??null; if(!is_string($txt)||trim($txt)==='') throw new RuntimeException('KI-Antwort konnte nicht ausgewertet werden.'); return $txt; }
function tr_parse_ai(string $raw,array $items): array { $txt=trim($raw); if(preg_match('/```(?:json)?\s*(.*?)```/is',$txt,$m))$txt=trim($m[1]); $j=json_decode($txt,true); if(!is_array($j)) throw new RuntimeException('KI-Antwort konnte nicht ausgewertet werden: '.json_last_error_msg()); $list=$j['suggestions']??$j['recommendations']??[]; if(!is_array($list)) throw new RuntimeException('KI-Antwort konnte nicht ausgewertet werden.'); $valid=[]; $ctx=[]; foreach($items as $it)$ctx[(int)$it['report_id'].':'.(int)$it['field_id']]=$it; foreach($list as $s){ if(!is_array($s))continue; $rid=(int)($s['report_id']??0); $fid=(int)($s['field_id']??0); if(!$rid||!$fid||!isset($ctx[$rid.':'.$fid]))continue; $it=$ctx[$rid.':'.$fid]; $valid[]=['student_id'=>(int)($s['student_id']??$it['student_id']),'student_name'=>(string)$it['student_name'],'report_id'=>$rid,'field_id'=>$fid,'field_label'=>(string)($it['field_label_de']?:$it['field_name']),'type'=>(string)($s['type']??'style'),'severity'=>(string)($s['severity']??'medium'),'original_excerpt'=>(string)($s['original_excerpt']??''),'suggested_text'=>(string)($s['suggested_text']??''),'explanation'=>(string)($s['explanation']??''),'confidence'=>(float)($s['confidence']??0.7),'original_text'=>(string)$it['current_text']]; } return $valid; }
function tr_run_batch(array $items): array { $cfg=tr_require_ai(); $tc=tr_cfg(); $maxFields=max(1,(int)($tc['max_fields_per_batch']??8)); $maxChars=max(1000,(int)($tc['max_chars_per_request']??12000)); $prepared=count($items); $skippedEmpty=0; $skippedTooLong=0; $selected=[]; $chars=0; foreach($items as $it){ if(!is_array($it))continue; $text=trim((string)($it['current_text']??'')); if($text===''){ $skippedEmpty++; continue; } $len=mb_strlen($text); if(count($selected)>=$maxFields || $chars+$len>$maxChars){ $skippedTooLong++; continue; } $it['current_text']=$text; $selected[]=$it; $chars+=$len; } if(!$selected) return ['ok'=>true,'checked'=>true,'no_issues'=>true,'suggestions'=>[],'diagnostics'=>['prepared'=>$prepared,'checked'=>0,'skipped_empty'=>$skippedEmpty,'skipped_too_long'=>$skippedTooLong,'ai_requests'=>0,'suggestions'=>0,'model'=>$cfg['model'],'provider'=>'ai']]; $raw=tr_ai_call(tr_prompt($selected),$cfg); $suggestions=tr_parse_ai($raw,$selected); return ['ok'=>true,'checked'=>true,'no_issues'=>count($suggestions)===0,'suggestions'=>$suggestions,'diagnostics'=>['prepared'=>$prepared,'checked'=>count($selected),'skipped_empty'=>$skippedEmpty,'skipped_too_long'=>$skippedTooLong,'ai_requests'=>1,'suggestions'=>count($suggestions),'model'=>$cfg['model'],'provider'=>'ai']]; }

try{ $data=tr_body(); if(!isset($_POST['csrf_token']) && isset($data['csrf_token']))$_POST['csrf_token']=(string)$data['csrf_token']; csrf_verify(); $pdo=db(); $u=current_user(); $uid=(int)($u['id']??0); $classId=(int)($data['class_id']??0); if($classId<=0 && ($data['action']??'')!=='self_test')throw new RuntimeException('class_id fehlt.'); if($classId>0 && ($u['role']??'')!=='admin' && !user_can_access_class($pdo,$uid,$classId)) throw new RuntimeException('Keine Berechtigung.'); $action=(string)($data['action']??'status'); if($action==='status')tr_json(tr_status($pdo,$classId)); if($action==='prepare')tr_json(tr_prepare($pdo,$classId)); if($action==='run_batch')tr_json(tr_run_batch(is_array($data['items']??null)?$data['items']:[])); if($action==='self_test'){ if(($u['role']??'')!=='admin')throw new RuntimeException('Keine Berechtigung.'); tr_json(tr_run_batch([['student_id'=>0,'student_name'=>'Self-Test','report_id'=>1,'field_id'=>1,'field_name'=>'self_test_de','field_label_de'=>'Self-Test DE','current_text'=>'Der Schüler hat gute Fortschritte gemacht, aber er muss noch an seine Rechtschreibung arbeiten tun.'],['student_id'=>0,'student_name'=>'Self-Test','report_id'=>1,'field_id'=>2,'field_name'=>'self_test_en','field_label_de'=>'Self-Test EN','current_text'=>'He have made good progress and can works more independently.']])); } throw new RuntimeException('Unbekannte action.'); }catch(Throwable $e){ tr_json(['ok'=>false,'checked'=>false,'error'=>$e->getMessage(),'message'=>$e->getMessage()],400); }
