<?php
declare(strict_types=1);

require __DIR__ . '/../../bootstrap.php';
require __DIR__ . '/../../shared/text_snippets.php';
require_teacher();
header('Content-Type: application/json; charset=utf-8');

function tr_json(array $payload, int $status = 200): never { http_response_code($status); echo json_encode($payload, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function tr_body(): array { $raw=file_get_contents('php://input'); $j=$raw?json_decode($raw,true):[]; return is_array($j)?$j:[]; }
function tr_cfg(): array { $cfg=app_config(); $tc=$cfg['text_check']??[]; return is_array($tc)?$tc:[]; }
function tr_ai_cfg(): array {
  $cfg=app_config(); $tc=tr_cfg(); $ai=$cfg['ai']??[]; if(!is_array($ai))$ai=[];
  $key=trim((string)($ai['api_key'] ?? getenv('OPENAI_API_KEY') ?: ''));
  $model=trim((string)($tc['model'] ?? '')) ?: trim((string)($ai['model'] ?? 'gpt-4o-mini'));
  return ['enabled'=>!empty($ai['enabled']),'api_key'=>$key,'base_url'=>rtrim((string)($ai['base_url']??'https://api.openai.com'),'/'),'model'=>$model,'timeout'=>(int)($ai['timeout_seconds']??60),'provider'=>(string)($tc['provider']??'disabled'),'text_enabled'=>!empty($tc['enabled'])];
}
function tr_enabled(): bool { $c=tr_ai_cfg(); return !empty($c['text_enabled']) && $c['provider']==='ai' && !empty($c['enabled']) && $c['api_key']!=='' && $c['model']!==''; }
function tr_require_ai(): array { $c=tr_ai_cfg(); if(empty($c['text_enabled'])||$c['provider']==='disabled') throw new RuntimeException('Textprüfung ist nicht konfiguriert.'); if($c['provider']!=='ai') throw new RuntimeException('KI-Provider nicht verfügbar.'); if(empty($c['enabled'])) throw new RuntimeException('KI-Provider nicht verfügbar.'); if($c['api_key']==='') throw new RuntimeException('API-Key fehlt.'); if($c['model']==='') throw new RuntimeException('Modell fehlt.'); return $c; }
function tr_is_free_text(array $f): bool { $t=strtolower((string)($f['field_type']??'')); return $t==='text'||$t==='multiline'||(int)($f['is_multiline']??0)===1; }
function tr_snippet_categories_from_meta(array $meta): ?array { $raw=$meta['snippet_categories']??null; if(is_string($raw))$raw=array_filter(array_map('trim',explode(',', $raw))); if(!is_array($raw))return null; $out=[]; foreach($raw as $v){$v=trim((string)$v); if($v!=='')$out[]=$v;} return $out?:null; }
function tr_snippet_category_ids_from_meta(array $meta): ?array { $raw=$meta['snippet_category_ids']??($meta['snippet_categories_ids']??null); if(is_string($raw))$raw=array_filter(array_map('trim',explode(',', $raw))); if(!is_array($raw))return null; $out=[]; foreach($raw as $v){$v=trim((string)$v); if($v!=='')$out[]=$v;} return $out?:null; }
function tr_load_snippets(PDO $pdo): array { $st=$pdo->query("SELECT id, category, content FROM text_snippets WHERE is_deleted=0 AND CHAR_LENGTH(TRIM(content))>=25 ORDER BY CHAR_LENGTH(content) DESC, id ASC"); $rows=[]; foreach($st->fetchAll(PDO::FETCH_ASSOC) as $r){ $content=trim((string)($r['content']??'')); if($content==='')continue; $cat=(string)($r['category']??''); $rows[]=['id'=>(int)$r['id'],'category'=>$cat,'category_id'=>text_snippet_category_id($cat),'content'=>$content,'length'=>strlen($content)]; } return $rows; }
function tr_relevant_snippets(array $all,array $field): array { $meta=json_decode((string)($field['meta_json']??''),true); $meta=is_array($meta)?$meta:[]; $ids=tr_snippet_category_ids_from_meta($meta); $cats=tr_snippet_categories_from_meta($meta); return array_values(array_filter($all,function($s)use($ids,$cats){ if($ids!==null)return $s['category_id']!==''&&in_array($s['category_id'],$ids,true); if($cats!==null)return in_array((string)$s['category'],$cats,true); return true; })); }
function tr_snippet_pattern(string $snippet): string { $quoted=preg_quote($snippet,'/'); return '/'.preg_replace('/(?:\\\s|\s)+/u','\\s+', $quoted).'/u'; }
function tr_find_snippet_ranges(string $text,array $snippets): array { $candidates=[]; foreach($snippets as $s){ if(mb_strlen($s['content'])<25)continue; $pattern=tr_snippet_pattern($s['content']); if(@preg_match_all($pattern,$text,$m,PREG_OFFSET_CAPTURE)){ foreach($m[0] as $hit){ $match=(string)$hit[0]; $start=(int)$hit[1]; $len=strlen($match); if($len>=25)$candidates[]=['start'=>$start,'length'=>$len,'end'=>$start+$len,'source_id'=>(int)$s['id'],'text'=>$match]; } } } usort($candidates,fn($a,$b)=>($b['length']<=>$a['length'])?:($a['start']<=>$b['start'])); $picked=[]; foreach($candidates as $c){ $over=false; foreach($picked as $p){ if($c['start']<$p['end'] && $c['end']>$p['start']){ $over=true; break; } } if(!$over)$picked[]=$c; } usort($picked,fn($a,$b)=>$a['start']<=>$b['start']); return $picked; }
function tr_text_without_ranges(string $text,array $ranges): string { if(!$ranges)return $text; $parts=[]; $pos=0; foreach($ranges as $r){ $start=(int)$r['start']; if($start>$pos)$parts[]=substr($text,$pos,$start-$pos); $pos=(int)$r['end']; } if($pos<strlen($text))$parts[]=substr($text,$pos); return trim(preg_replace('/\s{2,}/u',' ',implode("\n",array_map('trim',$parts)))??''); }
function tr_reports(PDO $pdo,int $classId,int $tplId,string $year,string $period): array { $st=$pdo->prepare("SELECT s.id student_id, CONCAT(s.last_name, ', ', s.first_name) student_name, ri.id report_id FROM students s JOIN report_instances ri ON ri.student_id=s.id AND ri.template_id=? AND ri.school_year=? AND ri.period_label=? WHERE s.class_id=? AND s.is_active=1 ORDER BY s.last_name,s.first_name,s.id"); $st->execute([$tplId,$year,$period,$classId]); return $st->fetchAll(PDO::FETCH_ASSOC); }
function tr_class_context(PDO $pdo,int $classId): array { $st=$pdo->prepare("SELECT id, template_id, school_year, period_label FROM classes WHERE id=? LIMIT 1"); $st->execute([$classId]); $c=$st->fetch(PDO::FETCH_ASSOC); if(!$c) throw new RuntimeException('Klasse nicht gefunden.'); return ['template_id'=>(int)$c['template_id'],'school_year'=>(string)$c['school_year'],'period_label'=>normalize_class_period_label($c['period_label']??'Standard')]; }
function tr_status(PDO $pdo,int $classId): array {
  $ctx=tr_class_context($pdo,$classId); $tplId=$ctx['template_id'];
  $fields=$pdo->prepare("SELECT id, can_teacher_edit, can_child_edit, is_required, field_type, is_multiline, field_name, label, label_en, meta_json FROM template_fields WHERE template_id=?"); $fields->execute([$tplId]); $rows=$fields->fetchAll(PDO::FETCH_ASSOC);
  $reqTeacher=[]; $reqChild=[]; $free=[];
  foreach($rows as $f){ $meta=json_decode((string)($f['meta_json']??''),true); $meta=is_array($meta)?$meta:[]; $sys=(!empty($meta['system_binding'])||!empty($meta['system_binding_tpl'])); $class=((string)($meta['scope']??'')==='class'||(int)($meta['is_class_field']??0)===1); if($sys||$class) continue; if((int)$f['is_required']===1 && (int)$f['can_teacher_edit']===1)$reqTeacher[]=(int)$f['id']; if((int)$f['is_required']===1 && (int)$f['can_child_edit']===1)$reqChild[]=(int)$f['id']; if((int)$f['can_teacher_edit']===1 && tr_is_free_text($f))$free[(int)$f['id']]=$f; }
  $reports=tr_reports($pdo,$classId,$tplId,$ctx['school_year'],$ctx['period_label']); $unfinished=0; $missing=0;
  $checkVals=function(array $ids,string $source)use($pdo,$reports){ if(!$ids||!$reports)return[]; $rids=array_map(fn($r)=>(int)$r['report_id'],$reports); $inR=implode(',',array_fill(0,count($rids),'?')); $inF=implode(',',array_fill(0,count($ids),'?')); $st=$pdo->prepare("SELECT report_instance_id,template_field_id,value_text FROM field_values WHERE source=? AND report_instance_id IN ($inR) AND template_field_id IN ($inF)"); $st->execute(array_merge([$source],$rids,$ids)); $out=[]; foreach($st->fetchAll(PDO::FETCH_ASSOC) as $v)$out[(int)$v['report_instance_id']][(int)$v['template_field_id']]=(string)($v['value_text']??''); return$out; };
  $tv=$checkVals($reqTeacher,'teacher'); $cv=$checkVals($reqChild,'child');
  foreach($reports as $r){$rid=(int)$r['report_id'];$miss=0;foreach($reqTeacher as $fid) if(trim($tv[$rid][$fid]??'')==='')$miss++; foreach($reqChild as $fid) if(trim($cv[$rid][$fid]??'')==='')$miss++; if($miss>0){$unfinished++;$missing+=$miss;}}
  $ai=tr_ai_cfg(); $tc=tr_cfg(); return ['ok'=>true,'enabled'=>tr_enabled(),'provider'=>$ai['provider'],'model'=>$ai['model'],'max_fields_per_batch'=>max(1,(int)($tc['max_fields_per_batch']??8)),'available'=>tr_enabled()&&$unfinished===0,'unfinished_reports'=>$unfinished,'missing_required_fields'=>$missing,'students_total'=>count($reports),'free_text_fields_total'=>count($free),'message'=>tr_enabled()?($unfinished===0?'':'Textprüfung verfügbar, sobald alle Pflichtfelder abgeschlossen sind.'):'Textprüfung ist derzeit nicht verfügbar.'];
}
function tr_prepare(PDO $pdo,int $classId): array { $s=tr_status($pdo,$classId); if(!$s['available']) return $s+['items'=>[],'estimated_chars'=>0,'snippet_diagnostics'=>[]]; $ctx=tr_class_context($pdo,$classId); $tplId=$ctx['template_id']; $reports=tr_reports($pdo,$classId,$tplId,$ctx['school_year'],$ctx['period_label']); $fields=$pdo->prepare("SELECT id, field_name, label, label_en, field_type, is_multiline, meta_json FROM template_fields WHERE template_id=? AND can_teacher_edit=1"); $fields->execute([$tplId]); $allSnippets=tr_load_snippets($pdo); $free=[]; foreach($fields->fetchAll(PDO::FETCH_ASSOC) as $f) if(tr_is_free_text($f))$free[(int)$f['id']]=$f; if(!$free||!$reports)return$s+['items'=>[],'estimated_chars'=>0,'snippet_diagnostics'=>[]]; $rids=array_map(fn($r)=>(int)$r['report_id'],$reports); $inR=implode(',',array_fill(0,count($rids),'?')); $inF=implode(',',array_fill(0,count($free),'?')); $st=$pdo->prepare("SELECT report_instance_id,template_field_id,value_text FROM field_values WHERE source='teacher' AND report_instance_id IN ($inR) AND template_field_id IN ($inF)"); $st->execute(array_merge($rids,array_keys($free))); $byReport=[]; foreach($reports as $r)$byReport[(int)$r['report_id']]=$r; $items=[];$chars=0;$diag=['fields_with_snippet_parts'=>0,'skipped_snippet_only'=>0,'snippet_chars_removed'=>0,'original_chars_total'=>0,'free_text_chars_sent'=>0]; foreach($st->fetchAll(PDO::FETCH_ASSOC) as $v){$text=trim((string)($v['value_text']??'')); if($text==='')continue; $fid=(int)$v['template_field_id']; $rid=(int)$v['report_instance_id']; $f=$free[$fid]; $r=$byReport[$rid]; $snips=tr_relevant_snippets($allSnippets,$f); $ranges=tr_find_snippet_ranges($text,$snips); $check=tr_text_without_ranges($text,$ranges); $origLen=mb_strlen($text); $checkLen=mb_strlen($check); $removed=max(0,$origLen-$checkLen); $diag['original_chars_total']+=$origLen; $diag['free_text_chars_sent']+=$checkLen; if($ranges){$diag['fields_with_snippet_parts']++; $diag['snippet_chars_removed']+=$removed;} $chars+=$checkLen; $item=['student_id'=>(int)$r['student_id'],'student_name'=>(string)$r['student_name'],'report_id'=>$rid,'field_id'=>$fid,'field_name'=>(string)$f['field_name'],'field_label_de'=>(string)($f['label']??''),'field_label_en'=>(string)($f['label_en']??''),'language'=>'auto','current_text'=>$check,'original_text'=>$text,'snippet_ranges'=>array_map(fn($rg)=>['start'=>(int)$rg['start'],'length'=>(int)$rg['length'],'source_id'=>(int)$rg['source_id'],'text_hash'=>hash('sha256',(string)$rg['text']),'text'=>(string)$rg['text']],$ranges)]; if($check===''){ $item['skip_reason']='snippet_only'; $diag['skipped_snippet_only']++; } $items[]=$item; } return $s+['items'=>$items,'estimated_chars'=>$chars,'snippet_diagnostics'=>$diag]; }
function tr_prompt(array $items): array { return [['role'=>'system','content'=>'Prüfe aktiv ausschließlich die frei geschriebenen Anteile von Lernentwicklungsbericht-/Zeugnis-Freitexten auf Rechtschreibung, Grammatik, Zeichensetzung, Sprachstil, Verständlichkeit und sachlichen Zeugnisstil. Textbausteinbereiche wurden vorab entfernt; erfinde keine Übergänge wegen fehlendem Kontext. Gib Empfehlungen nur für die gesendeten frei geschriebenen Textteile. Bei offensichtlichen Fehlern MUSS eine Empfehlung kommen. Behalte Bedeutung, Bewertung und Aussageabsicht bei. Erfinde keine Inhalte und ergänze keine Beobachtungen. Mache konkrete, minimal-invasive Vorschläge. Antworte ausschließlich als valides JSON: {"suggestions":[{"student_id":number,"report_id":number,"field_id":number,"type":"spelling|grammar|style|translation","severity":"low|medium|high","original_excerpt":"...","suggested_text":"...","explanation":"...","confidence":0.0-1.0}]}. Wenn wirklich nichts zu verbessern ist, suggestions: []. Beispiele: Input "He have made good progress." => grammar Vorschlag "He has made good progress." Input "Der Schüler arbeitet gut mit tun." => grammar/style Vorschlag "Der Schüler arbeitet gut mit."'],['role'=>'user','content'=>json_encode(['items'=>$items],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]]; }
function tr_ai_call(array $messages,array $cfg): string { if(!function_exists('curl_init')) throw new RuntimeException('KI-Provider nicht verfügbar: PHP-cURL fehlt.'); $url=$cfg['base_url'].'/v1/chat/completions'; $payload=['model'=>$cfg['model'],'messages'=>$messages,'temperature'=>0.1,'response_format'=>['type'=>'json_object']]; $ch=curl_init($url); if(!$ch) throw new RuntimeException('KI-Provider nicht verfügbar.'); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Authorization: Bearer '.$cfg['api_key']],CURLOPT_POSTFIELDS=>json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),CURLOPT_TIMEOUT=>max(10,(int)$cfg['timeout'])]); $resp=curl_exec($ch); $code=(int)(curl_getinfo($ch,CURLINFO_HTTP_CODE)?:0); if($resp===false){$err=curl_error($ch);curl_close($ch);throw new RuntimeException('KI-Provider nicht verfügbar: '.$err);} curl_close($ch); $j=json_decode((string)$resp,true); if($code<200||$code>=300) throw new RuntimeException('KI-Fehler: HTTP '.$code); $txt=$j['choices'][0]['message']['content']??null; if(!is_string($txt)||trim($txt)==='') throw new RuntimeException('KI-Antwort konnte nicht ausgewertet werden.'); return $txt; }
function tr_parse_ai(string $raw,array $items): array { $txt=trim($raw); if(preg_match('/```(?:json)?\s*(.*?)```/is',$txt,$m))$txt=trim($m[1]); $j=json_decode($txt,true); if(!is_array($j)) throw new RuntimeException('KI-Antwort konnte nicht ausgewertet werden: '.json_last_error_msg()); $list=$j['suggestions']??$j['recommendations']??[]; if(!is_array($list)) throw new RuntimeException('KI-Antwort konnte nicht ausgewertet werden.'); $valid=[]; $ctx=[]; foreach($items as $it)$ctx[(int)$it['report_id'].':'.(int)$it['field_id']]=$it; foreach($list as $s){ if(!is_array($s))continue; $rid=(int)($s['report_id']??0); $fid=(int)($s['field_id']??0); if(!$rid||!$fid||!isset($ctx[$rid.':'.$fid]))continue; $it=$ctx[$rid.':'.$fid]; $valid[]=['student_id'=>(int)($s['student_id']??$it['student_id']),'student_name'=>(string)$it['student_name'],'report_id'=>$rid,'field_id'=>$fid,'field_label'=>(string)($it['field_label_de']?:$it['field_name']),'type'=>(string)($s['type']??'style'),'severity'=>(string)($s['severity']??'medium'),'original_excerpt'=>(string)($s['original_excerpt']??''),'suggested_text'=>(string)($s['suggested_text']??''),'explanation'=>(string)($s['explanation']??''),'confidence'=>(float)($s['confidence']??0.7),'original_text'=>(string)($it['original_text']??$it['current_text']),'snippet_ranges'=>is_array($it['snippet_ranges']??null)?$it['snippet_ranges']:[]]; } return $valid; }
function tr_run_batch(array $items): array { $cfg=tr_require_ai(); $tc=tr_cfg(); $maxFields=max(1,(int)($tc['max_fields_per_batch']??8)); $maxChars=max(1000,(int)($tc['max_chars_per_request']??12000)); $prepared=count($items); $skippedEmpty=0; $skippedSnippet=0; $skippedTooLong=0; $fieldsWithSnippets=0; $snippetCharsRemoved=0; $originalChars=0; $selected=[]; $chars=0; foreach($items as $it){ if(!is_array($it))continue; $orig=(string)($it['original_text']??($it['current_text']??'')); $text=trim((string)($it['current_text']??'')); $ranges=is_array($it['snippet_ranges']??null)?$it['snippet_ranges']:[]; $originalChars+=mb_strlen($orig); if($ranges){$fieldsWithSnippets++; $snippetCharsRemoved+=max(0,mb_strlen($orig)-mb_strlen($text));} if(($it['skip_reason']??'')==='snippet_only'){ $skippedSnippet++; continue; } if($text===''){ $skippedEmpty++; continue; } $len=mb_strlen($text); if(count($selected)>=$maxFields || $chars+$len>$maxChars){ $skippedTooLong++; continue; } $it['current_text']=$text; $selected[]=$it; $chars+=$len; } $diag=['prepared'=>$prepared,'checked'=>count($selected),'skipped_empty'=>$skippedEmpty,'skipped_snippet_only'=>$skippedSnippet,'skipped_too_long'=>$skippedTooLong,'fields_with_snippet_parts'=>$fieldsWithSnippets,'snippet_chars_removed'=>$snippetCharsRemoved,'free_text_chars_sent'=>$chars,'original_chars_total'=>$originalChars,'ai_requests'=>0,'suggestions'=>0,'model'=>$cfg['model'],'provider'=>'ai']; if(!$selected) return ['ok'=>true,'checked'=>true,'no_issues'=>true,'suggestions'=>[],'diagnostics'=>$diag]; $raw=tr_ai_call(tr_prompt($selected),$cfg); $suggestions=tr_parse_ai($raw,$selected); $diag['ai_requests']=1; $diag['suggestions']=count($suggestions); return ['ok'=>true,'checked'=>true,'no_issues'=>count($suggestions)===0,'suggestions'=>$suggestions,'diagnostics'=>$diag]; }

try{ $data=tr_body(); if(!isset($_POST['csrf_token']) && isset($data['csrf_token']))$_POST['csrf_token']=(string)$data['csrf_token']; csrf_verify(); $pdo=db(); $u=current_user(); $uid=(int)($u['id']??0); $classId=(int)($data['class_id']??0); if($classId<=0 && ($data['action']??'')!=='self_test')throw new RuntimeException('class_id fehlt.'); if($classId>0 && ($u['role']??'')!=='admin' && !user_can_access_class($pdo,$uid,$classId)) throw new RuntimeException('Keine Berechtigung.'); $action=(string)($data['action']??'status'); if($action==='status')tr_json(tr_status($pdo,$classId)); if($action==='prepare')tr_json(tr_prepare($pdo,$classId)); if($action==='run_batch')tr_json(tr_run_batch(is_array($data['items']??null)?$data['items']:[])); if($action==='self_test'){ if(($u['role']??'')!=='admin')throw new RuntimeException('Keine Berechtigung.'); tr_json(tr_run_batch([['student_id'=>0,'student_name'=>'Self-Test','report_id'=>1,'field_id'=>1,'field_name'=>'self_test_de','field_label_de'=>'Self-Test DE','current_text'=>'Der Schüler hat gute Fortschritte gemacht, aber er muss noch an seine Rechtschreibung arbeiten tun.'],['student_id'=>0,'student_name'=>'Self-Test','report_id'=>1,'field_id'=>2,'field_name'=>'self_test_en','field_label_de'=>'Self-Test EN','current_text'=>'He have made good progress and can works more independently.']])); } throw new RuntimeException('Unbekannte action.'); }catch(Throwable $e){ tr_json(['ok'=>false,'checked'=>false,'error'=>$e->getMessage(),'message'=>$e->getMessage()],400); }
