<?php
declare(strict_types=1);
require __DIR__ . '/../bootstrap.php'; require __DIR__ . '/_layout.php'; require_admin();
$pdo=db(); $ok=null; $err=null;
$gradeOptions=[1,2,3,4,5,6,7,8,9,10,11,12,13];
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{ csrf_verify(); $a=(string)($_POST['action']??'');
    if($a==='add_category'){ $pdo->prepare("INSERT INTO competency_categories(name_de,name_en,sort_order) VALUES (?,?,?)")->execute([trim((string)$_POST['name_de']),trim((string)($_POST['name_en']??'')),(int)($_POST['sort_order']??0)]); }
    if($a==='add_subcategory'){ $pdo->prepare("INSERT INTO competency_subcategories(category_id,name_de,name_en,sort_order) VALUES (?,?,?,?)")->execute([(int)$_POST['category_id'],trim((string)$_POST['name_de']),trim((string)($_POST['name_en']??'')),(int)($_POST['sort_order']??0)]); }
    if($a==='add_competency'){ $pdo->prepare("INSERT INTO competencies(subcategory_id,code,text_de,text_en,is_required,sort_order) VALUES (?,?,?,?,?,?)")->execute([(int)$_POST['subcategory_id'],trim((string)($_POST['code']??'')),trim((string)$_POST['text_de']),trim((string)($_POST['text_en']??'')),isset($_POST['is_required'])?1:0,(int)($_POST['sort_order']??0)]); $cid=(int)$pdo->lastInsertId(); foreach((array)($_POST['grades']??[]) as $g){$pdo->prepare("INSERT INTO competency_grade_levels(competency_id,grade_level) VALUES (?,?)")->execute([$cid,(int)$g]);}}
    if($a==='csv_import'){ if(!isset($_FILES['csv'])||!is_uploaded_file($_FILES['csv']['tmp_name'])) throw new RuntimeException('CSV fehlt'); $fh=fopen($_FILES['csv']['tmp_name'],'r'); $n=0; while(($r=fgetcsv($fh,0,';'))!==false){ if(count($r)<6||$n===0){$n++;continue;} [$cat,$sub,$de,$en,$required,$grades]=$r; $pdo->prepare("INSERT INTO competency_categories(name_de,name_en,sort_order) VALUES (?,?,0) ON DUPLICATE KEY UPDATE name_de=name_de")->execute([$cat,$cat]); $catId=(int)$pdo->query("SELECT id FROM competency_categories WHERE name_de=".$pdo->quote($cat)." LIMIT 1")->fetchColumn(); $pdo->prepare("INSERT INTO competency_subcategories(category_id,name_de,name_en,sort_order) VALUES (?,?,?,0)")->execute([$catId,$sub,$sub]); $subId=(int)$pdo->lastInsertId(); $pdo->prepare("INSERT INTO competencies(subcategory_id,text_de,text_en,is_required,sort_order) VALUES (?,?,?,?,0)")->execute([$subId,$de,$en,(trim(strtolower($required))==='1'||trim(strtolower($required))==='ja')?1:0]); $cid=(int)$pdo->lastInsertId(); foreach(explode(',',(string)$grades) as $g){$g=(int)trim($g); if($g>0){$pdo->prepare("INSERT IGNORE INTO competency_grade_levels(competency_id,grade_level) VALUES (?,?)")->execute([$cid,$g]);}} $n++; } if($fh)fclose($fh);
    }
    if($a==='review_request'){ $id=(int)$_POST['request_id']; $status=(string)$_POST['status']; $note=trim((string)($_POST['admin_note']??'')); $pdo->prepare("UPDATE competency_requests SET status=?, admin_note=?, reviewed_by_user_id=?, reviewed_at=NOW() WHERE id=?")->execute([$status,$note,(int)current_user()['id'],$id]); }
    $ok='Gespeichert.';
  }catch(Throwable $e){$err=$e->getMessage();}
}
$cats=$pdo->query("SELECT * FROM competency_categories ORDER BY sort_order,id")->fetchAll(PDO::FETCH_ASSOC);
$subs=$pdo->query("SELECT * FROM competency_subcategories ORDER BY category_id,sort_order,id")->fetchAll(PDO::FETCH_ASSOC);
$comps=$pdo->query("SELECT c.*,s.name_de AS sub_name,cat.name_de AS cat_name FROM competencies c JOIN competency_subcategories s ON s.id=c.subcategory_id JOIN competency_categories cat ON cat.id=s.category_id ORDER BY cat.sort_order,s.sort_order,c.sort_order,c.id")->fetchAll(PDO::FETCH_ASSOC);
$reqs=$pdo->query("SELECT r.*,u.display_name FROM competency_requests r JOIN users u ON u.id=r.teacher_user_id ORDER BY r.created_at DESC")->fetchAll(PDO::FETCH_ASSOC);
render_admin_header('Kompetenzen verwalten'); ?>
<div class="card"><h1>Kompetenzen verwalten</h1><?php if($ok):?><div class="alert success"><?=h($ok)?></div><?php endif; ?><?php if($err):?><div class="alert danger"><?=h($err)?></div><?php endif; ?></div>
<div class="card"><h3>CSV Import</h3><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="csv_import"><input type="file" name="csv" required><button class="btn">Importieren</button></form></div>
<div class="card"><h3>Kategorie hinzufügen</h3><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add_category"><input class="input" name="name_de" placeholder="Deutsch" required><input class="input" name="name_en" placeholder="Englisch"><button class="btn">Speichern</button></form></div>
<div class="card"><h3>Unterkategorie hinzufügen</h3><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add_subcategory"><select class="input" name="category_id"><?php foreach($cats as $c):?><option value="<?=$c['id']?>"><?=h($c['name_de'])?></option><?php endforeach;?></select><input class="input" name="name_de" required><input class="input" name="name_en"><button class="btn">Speichern</button></form></div>
<div class="card"><h3>Kompetenz hinzufügen</h3><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add_competency"><select class="input" name="subcategory_id"><?php foreach($subs as $s):?><option value="<?=$s['id']?>"><?=h($s['name_de'])?></option><?php endforeach;?></select><input class="input" name="code" placeholder="Code optional"><textarea class="input" name="text_de" required></textarea><textarea class="input" name="text_en"></textarea><label><input type="checkbox" name="is_required" value="1"> verpflichtend</label><div><?php foreach($gradeOptions as $g):?><label style="margin-right:8px;"><input type="checkbox" name="grades[]" value="<?=$g?>"> <?=$g?></label><?php endforeach;?></div><button class="btn">Speichern</button></form></div>
<div class="card"><h3>Anträge von Lehrkräften</h3><table class="table"><tr><th>Zeit</th><th>Lehrkraft</th><th>Vorschlag</th><th>Status</th><th>Aktion</th></tr><?php foreach($reqs as $r):?><tr><td><?=h((string)$r['created_at'])?></td><td><?=h((string)$r['display_name'])?></td><td><?=h((string)$r['proposal_text_de'])?></td><td><?=h((string)$r['status'])?></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="review_request"><input type="hidden" name="request_id" value="<?=$r['id']?>"><select name="status"><option>pending</option><option>approved</option><option>rejected</option></select><input name="admin_note" placeholder="Notiz"><button class="btn">Speichern</button></form></td></tr><?php endforeach;?></table></div>
<?php render_admin_footer();
